version: '3.8'

services:
  app:
    container_name: project_app
    build:
     context: .
     dockerfile: docker/php/Dockerfile
    networks:
      - project_net
    volumes:
      - ./src/:/var/www/html
      - ./logs/nginx:/var/log/nginx/
  server:
    container_name: project_server
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=9000
    networks:
      - project_net
    volumes:
      - ./src/:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
    ports:
      - '8000:80'

networks:
  project_net:
    driver: bridge
